version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - "5431:5432"
        volumes:
            - postgre-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=vinicius
            - POSTGRES_PASSWORD=teste
            - POSTGRES_DB=teste
    node.app:
        container_name: node.app
        build:
            context: ./
            dockerfile: node.Dockerfile
        command: node app.js
        depends_on:
            - postgres
        ports:
            - "3000:3000"
volumes:
    postgre-data:

networks:
    default: